name: MakeCode

on:
    push:
        branches:
            - main
            - master
        tags:
            - "v[0-9]*.*.*"
    pull_request:
        branches:
            - master
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: npm install
              run: |
                  npm install -g makecode@v0.34.6
            - run: makecode -u -j --mono-repo -c mkc.json
            - run: makecode -u -j --mono-repo -c mkc-maker.json
            - run: makecode -u -j --mono-repo -c mkc-arcade.json
            - run: makecode -u -j --mono-repo -c mkc-calliope.json
            - run: makecode -c mkc.json
            - run: makecode -c mkc-maker.json --hw nucleo-f411re
            - run: makecode -c mkc-arcade.json --hw F4,D5,N4,N3
            - run: cd tools/multitool && makecode --hw F4,D5,N4,N3
            - run: cd tools/uploader && makecode
            - run: cd tools/hid-servers && makecode
            - run: cd tools/hid-servers && makecode -c mkc-rp2040.json
            - run: cd tools/hid-joystick && makecode
            - run: cd tools/hid-joystick && makecode -c mkc-rp2040.json
            - run: cd tools/microbit-oob && makecode
            - run: cd tools/microbit-jukebox && makecode
            - run: cd tools/farm-beats && makecode
            - run: ./test-others.sh
            - run: ./copy-release-files.sh
            - name: Upload release files
              uses: actions/upload-artifact@v1
              with:
                  name: release-files
                  path: dist/
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: dist/*
